yarnPath: .yarn/releases/yarn-4.1.0.cjs
nodeLinker: node-modules
packageExtensions:
  "@nivo/core@*":
    dependencies:
      prop-types: "*"
      "@nivo/tooltip": "*"
  "@nivo/legends@*":
    dependencies:
      d3-scale: "*"
      "@nivo/colors": "*"
